# pytorch_lightning==1.7.3
seed_everything: 42
trainer:
  logger:
    - class_path: pytorch_lightning.loggers.WandbLogger
      init_args:
        project: vip-challenge
        dir: /mnt/hdd-data/beetz/vip/logs
        save_dir: /mnt/hdd-data/beetz/vip/logs
  enable_checkpointing: true
  default_root_dir: /mnt/hdd-data/beetz/vip/logs
  accelerator: gpu
  devices: [1]
  max_epochs: 25
data:
  data_dir: /mnt/hdd-data/DeepfakeIEEE/original
  batch_size: 256
  num_workers: 12
  num_train_samples: 20000
  num_val_samples: 1000
ckpt_path: null