# pytorch_lightning==1.7.3
seed_everything: 42
trainer:
  logger:
    - class_path: pytorch_lightning.loggers.WandbLogger
      init_args:
        project: vip-challenge
        dir: /mnt/hdd-data/beetz/vip/logs
        save_dir: /mnt/hdd-data/beetz/vip/logs
        log_model: True
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val/acc
        patience: 15
        mode: max
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val/acc
        mode: max
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
  enable_checkpointing: true
  default_root_dir: /mnt/hdd-data/beetz/vip/logs
  accelerator: gpu
  devices: [2]
  max_epochs: 50
data:
  data_dir: /mnt/hdd-data/DeepfakeIEEE/original
  batch_size: 32
  num_workers: 12
  num_train_samples: 20000
  num_val_samples: 10000
  test_data_path: /mnt/hdd-data/DeepfakeIEEE/notebooks/val_wsubset.pt
  timm_model_name: vit_base_patch16_224
model:
  timm_model_name: vit_base_patch16_224
  learning_rate: 3e-5
  weight_decay: 1e-5
ckpt_path: null